syntax = "proto3";

package one.instrument.twin;
option csharp_namespace = "ONE.Instrument.Twin";

import "google/protobuf/wrappers.proto";
import "record_auditinfo.proto";

message InstrumentTelemetryComplianceLimit {
    // Telemetry identifier from InstrumentDigitalTwins.
    google.protobuf.StringValue telemetryId = 2;

    // Indicates whether compliance monitoring is enabled
    // for this telemetry.
    google.protobuf.BoolValue enabled = 3;

    // Upper alarm threshold.
    google.protobuf.StringValue highAlarm = 4;

    // Upper warning threshold.
    google.protobuf.StringValue highWarning = 5;

    // Lower warning threshold.
    google.protobuf.StringValue lowWarning = 6;

    // Lower alarm threshold.
    google.protobuf.StringValue lowAlarm = 7;

    // Record audit information.
    RecordAuditInfo recordAuditInfo = 99;
}

message InstrumentTelemetryComplianceLimits {
    repeated InstrumentTelemetryComplianceLimit items = 1;
}

message InstrumentTelemetryComplianceLimitGroup {
    google.protobuf.StringValue instrumentId = 1;
    InstrumentTelemetryComplianceLimits instrumentTelemetryComplianceLimits = 2;
}

message InstrumentTelemetryComplianceLimitGroups {
    repeated InstrumentTelemetryComplianceLimitGroup items = 1;
}
