syntax = "proto3";

package one.instrument.twin;

option csharp_namespace = "ONE.Instrument.Twin";

import "google/protobuf/timestamp.proto";

message InstrumentTelemetryComplianceStatus
{
    // Instrument Digital Twin identifier.
    string instrumentId = 1;

    // Telemetry identifier.
    string telemetryId = 2;

    // Current compliance state.
    ComplianceState complianceState = 3;

    // Latest measurement value used for evaluation.
    double measurementValue = 4;

    // Timestamp of the latest measurement.
    google.protobuf.Timestamp measurementTimestamp = 5;

    // Timestamp when the compliance state last changed.
    google.protobuf.Timestamp stateChangedAt = 6;

    // Indicates whether the initial notification for the
    // current compliance condition has been sent.
    bool initialNotificationSent = 7;

    // UTC timestamp when the most recent notification was sent
    // for the current compliance condition.
    google.protobuf.Timestamp lastNotificationTimestamp = 8;
}

enum ComplianceState
{
    COMPLIANCE_STATE_UNSPECIFIED = 0;

    NORMAL = 1;

    HIGH_WARNING = 2;

    HIGH_ALARM = 3;

    LOW_WARNING = 4;

    LOW_ALARM = 5;
}

message InstrumentTelemetryComplianceStatuses {
  repeated InstrumentTelemetryComplianceStatus items = 1;
}
message InstrumentTelemetryComplianceStatusGroup {
    string instrumentId = 1;
    InstrumentTelemetryComplianceStatuses instrumentTelemetryComplianceStatuses = 2;
}
message InstrumentTelemetryComplianceStatusGroups {    
    repeated InstrumentTelemetryComplianceStatusGroup items = 1;
}